# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

plugins:
  - serverless-pseudo-parameters

service: SSLBot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: dev
  timeout: 900
  
  environment:
    AWS_LAMBDA: "1"
    DOMAINS: "${self:custom.domains.${self:custom.stage}}"
    LETSENCRYPT_EMAIL: "${self:custom.email}"
    STAGING: "${self:custom.acmeStaging.${self:custom.stage}}"
    NOTIFICATION_TOPIC: "#{SSLCerts}"
    RENEW_BEFORE: "30" # Days before expiration when you want to renew.

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "route53:ListHostedZones"
        - "cloudwatch:PutMetricData"
        - "acm:ImportCertificate"
        - "acm:ListCertificates"
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:*"
    - Effect: "Allow"
      Action: 
        - "route53:GetChange"
        - "route53:ChangeResourceRecordSets"
      Resource:
        - "arn:aws:route53:::hostedzone/*"
        - "arn:aws:route53:::change/*"
    - Effect: "Allow"
      Action: 
        - "acm:ImportCertificate"
        - "acm:DescribeCertificate"
      Resource:
        - "arn:aws:acm:#{AWS::Region}:#{AWS::AccountId}:certificate/*"

custom:
  stage: ${opt:stage, self:provider.stage}
  acmeStaging:
    dev: "1"
    prod: "0"
  email: ${ssm:/sslbot/email}
  domains:
    dev: ${ssm:/sslbot/dev/domains}
    prod: ${ssm:/sslbot/prod/domains}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  ProcessCerts:
    handler: bin/acme-dns-route53
    events:
      - schedule:
          name: "SSLBot-${self:custom.stage}-Renewal"
          description: "Renews Let's Encrypt certificates on specified schedule."
          rate: "rate(1 day)"

resources:
  Resources:
    SSLCerts:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "SSL Certification Notifications (${self:custom.stage})"
        TopicName: "SSLCertificationNotices-${self:custom.stage}"